inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "vendor/**/*"

require:
  - rubocop-rails
  - rubocop-capybara

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 100

Layout/LineLength:
  Max: 300 

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 10